config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'learnings#index'

  resources :learnings do
    collection do
      get :history
      get :search
    end
    member do
      post :check_item
      post :relearn
    end
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :users, only: [:show]

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/learning.rb
# frozen_string_literal: true

class Learning < ApplicationRecord
  before_validation :set_nameless_content

  validates :title, presence: true
  validates :title, length: { maximum: 1000 }
  validates :main_content, length: { maximum: 1000 }
  validates :sub_content, length: { maximum: 1000 }
  validates :url_info, length: { maximum: 1000 }

  attribute :checked_times, :integer, default: 0
  attribute :reappearance_date, :date, default: Date.today + 36_500

  mount_uploader :image, ImageUploader

  belongs_to :user, optional: true
  has_many :labelings, dependent: :destroy
  has_many :labels, through: :labelings

  def set_nameless_content
    self.main_content = '' if main_content.blank?
    self.sub_content = '' if sub_content.blank?
  end
end

app/controllers/learnings_controller.rb
# frozen_string_literal: true

class LearningsController < ApplicationController
  before_action :set_learning, only: %i[show edit update destroy check_item relearn]
  before_action :authenticate_user!

  def index
    if current_user.present?
      @learnings = current_user.learnings.where(reappearance_date: '1900-01-01'.to_date..Time.zone.today)
                                         .or(current_user.learnings.where(checked_times: 0))
                                           .page(params[:page])
                                           .per(10).order('created_on')
    else
      redirect_to login_url, notice: 'Please log in.'
    end
  end

  def search
    @q = current_user.learnings.search(search_params)
    @learnings = @q.result(distinct: true).page(params[:page]).per(10)
  end

  def history
    if current_user.present?
      @q = current_user.learnings.page(params[:page]).ransack(params[:q])
      @learnings = @q.result(distinct: true).page(params[:page]).per(10).per(10).order('created_on')
    else
      redirect_to login_url, notice: 'Please log in.'
    end
  end

  def check_item
    @learning.checked_times += 1
    @learning.checked_on = Date.today
    @learning.reappearance_date = case @learning.checked_times
                                  when 1
                                    @learning.created_on + 86_400
                                  when 2
                                    @learning.created_on + 3 * 86_400
                                  when 3
                                    @learning.created_on + 7 * 86_400
                                  when 4
                                    @learning.created_on + 14 * 86_400
                                  else
                                    @learning.created_on + 30 * 86_400
                                  end
    @learning.save
    redirect_to learnings_path, notice: "次回学習日 #{@learning.reappearance_date}"
  end

  def relearn
    @learning.checked_times = 0
    @learning.save
    redirect_to learnings_path, notice: "項目「#{@learning.title}を再学習します。"
  end

  def new
    @learning = Learning.new
  end

  def create
    @learning = current_user.learnings.create(learning_params)
    if @learning.save
      redirect_to learnings_url, notice: "項目「#{@learning.title}」を登録しました。"
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @learning.update(learning_params)
      redirect_to learnings_path, notice: "項目「#{@learning.title}」を編集しました"
    else
      render :edit
    end
  end

  def destroy
    @learning.destroy
    redirect_to learnings_path, notice: '項目を削除しました'
  end

  private

  def set_learning
    @learning = current_user.learnings.find(params[:id])
  end

  def learning_params
    params.require(:learning).permit(:title, { label_ids: [] },
                                     :main_content,
                                     :sub_content,
                                     :url_info,
                                     :image,
                                     :image_cache,
                                     :checked_on,
                                     :reappearance_date,
                                     :checked_times)
  end

  def search_params
    params.require(:q).permit!
  end
end

app/helpers/learnings_helper.rb
# frozen_string_literal: true

module LearningsHelper
end

app/views/learnings/_learning_form.html.erb
<%= form_with(model: @learning, local: true) do |form| %>
  <% if @learning.errors.any? %>
     <div id="error_explanation">
       <h2><%= @learning.errors.count %>件のエラーがあります。</h2>
       <ul>
       <% @learning.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
       <% end %>
       </ul>
     </div>
   <% end %>
  <div class="form-group">
    <%= form.label :title %><br>
    <%= form.text_field :title, placeholder: "覚えたいこと：問" %>
  </div>
    <div class="form-group">
      <%= form.label :main_content %><br>
      <%= form.text_area :main_content, placeholder: "覚えたいこと：答", size: "50x3" %>
    </div>
  <div class="form-group">
    <%= form.label :url_info %><br>
    <%= form.text_field :url_info, placeholder: "読み返したいサイト" %>
  </div>
    <div class="actions">
      <%= form.submit "保存", class: "btn btn-success", id: 12 %>
    </div>
  <div class="form-group">
    <br>
    <%= form.label :sub_content %><br>
    <%= form.text_area :sub_content, placeholder: "本項についての補足事項", size: "50x3" %>
  </div>
    <div class="form-group">
      <%= form.label :image %>
      <%= image_tag(@learning.image.url) if @learning.image && @learning.image.url %><br>
      <%= form.file_field :image %>
      <% form.hidden_field :image_cache %>
    </div>
  <div class="form-group">
    <%= form.label :label %><br>
    <%= form.collection_check_boxes(:label_ids, Label.all, :id, :label_name) %>
  </div>
    <div class="actions">
      <%= form.submit "保存", class: "btn btn-success" %>
    </div>
<% end %>

app/views/learnings/_search_form.html.erb
<%= search_form_for @q do |f| %>
  <%= f.label :"" %>
  <%= f.search_field :title_or_main_content_or_sub_content_or_labels_label_name_cont %>
  <%= f.submit %>
<% end %>

app/views/learnings/edit.html.erb
<div class="container">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-9">
      <h2><%= t('.Editing Item') %></h2>
        <%= render 'learning_form', learning: @learning %>
          <br>
        <div class="btn-group">
        <%= link_to '一覧に戻る', learnings_path, class: "btn btn-secondary" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/learnings/history.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1><%= t('.Index') %></h1>
    </div>
  <div class="col">
    <br>
      <%= search_form_for @q, :url => history_learnings_path do |f| %>
      <%= f.label :"" %>
      <%= f.search_field :title_or_main_content_or_sub_content_or_labels_label_name_cont %>
      <%= f.submit '検索', class: "btn btn-secondary" %>
    <% end %>
  </div>
</div>
  <div class="col">
    <br>
      <%= paginate @learnings %>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-9">
      <% @learnings.each_with_index do |l, index| %>
      <div class="card mb-3">
        <div class="card-header h4"><%= l.title %></div>
          <div class="card-body">
            <div class="d-flex justify-content-center">
              <p class="card-text"><%= image_tag(l.image.url) if l.image && l.image.url %></p>
            </div>
          <div class="d-flex justify-content-center">
            <p class="card-text"><%= link_to 'URL', l.url_info, target: :_blank  unless l.url_info.blank? %></p>
          </div>
            <div class="accordion d-flex justify-content-center" id="accordion">
              <div class="card w-100 border-white">
                <div class="card-header h4  bg-transparent" id="headingOne">
                  <h5 class="mb-0">
                    <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapse_<%= index %>" aria-expanded="true" aria-controls="collapse_<%= index %>"> 本文を読む
                    </button>
                  </h5>
                </div>
                <div id="collapse_<%= index %>" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
                  <div class="card-body bg-light">
                    <p class="card-text"><%= l.main_content %></p>
                    <p class="card-text"><%= l.sub_content %></p>
                  </div>
                </div>
              </div>
            </div>
            <div class="card-text d-flex flex-wrap">
                <% l.labelings.each do |lbl| %>
                <div class="flex-wrap">
                  <%= lbl.label.label_name %>
                </div>
                <% end %>
            </div>
            <div class="d-flex">
              <div class="card-text mr-auto">チェック回数：<%= l.checked_times %></div>
              <div><%= simple_date(l.created_on) %>作成</div>
            </div>
          </div>
            <div class="card-footer bg-transparent">
              <div class="btn-group d-flex justify-content-around" role="group">
                  <%= link_to('削除', learning_path(l.id),
                      { method: :delete,
                        data: { confirm: "項目#{l.title}を削除します"},
                        class: "btn btn-info"
                      }
                    )
                  %>
                  <%= link_to("再学習", relearn_learning_path(l.id),
                      { method: :relearn,
                        data: { confirm: "項目#{l.title}を再学習します"},
                        class: "btn btn-info"
                      }
                    )
                  %>
                  <%= link_to "編集", edit_learning_path(l.id), class: "btn btn-info" %>

                  <%= link_to "チェック", check_item_learning_path(l.id),
                      { method: :check_item,
                        class: "btn btn-success"
                      }
                  %>
              </div>
            </div>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/learnings/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <h1><%= t('.Index') %></h1>
      <br>
    </div>
      <div class="col-md-9">
        <%= paginate @learnings %>
      </div>
  </div>
</div>
  <div class="container-fluid scroll-bg">
    <div class="row">
      <div class="col-md-9">
        <% @learnings.each_with_index do |l, index| %>
        <div class="card mb-3">
          <div class="card-header h4"><%= l.title %></div>
            <div class="card-body">
              <div class="d-flex justify-content-center">
                <p class="card-text"><%= image_tag(l.image.url) if l.image && l.image.url %></p>
              </div>
              <div class="d-flex justify-content-center">
                <p class="card-text"><%= link_to 'URL', l.url_info, target: :_blank  unless l.url_info.blank? %></p>
              </div>
              <% unless l.main_content.blank? %>
              <div class="accordion d-flex justify-content-center" id="accordion">
                <div class="card w-100 border-white">
                  <div class="card-header h4  bg-transparent" id="headingOne">
                    <h5 class="mb-0">
                      <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapse_<%= index %>" aria-expanded="true" aria-controls="collapse_<%= index %>">本文を読む
                      </button>
                    </h5>
                  </div>
                  <div id="collapse_<%= index %>" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
                    <div class="card-body bg-light">
                      <p class="card-text"><%= l.main_content %></p>
                      <p class="card-text"><%= l.sub_content %></p>
                    </div>
                  </div>
                </div>
              </div>
                <% end %>
              <div class="card-text d-flex flex-wrap">
                  <% l.labelings.each do |lbl| %>
                  <div class="flex-wrap">
                    <%= lbl.label.label_name %>
                  </div>
                <% end %>
              </div>
            <div class="d-flex">
              <div class="card-text mr-auto">チェック回数：<%= l.checked_times %></div>
                <div><%= simple_date(l.created_on) %>作成</div>
            </div>
          </div>
            <div class="card-footer bg-transparent">
              <div class="btn-group d-flex justify-content-around" role="group">
                  <%= link_to('削除', learning_path(l.id),
                      { method: :delete,
                        data: { confirm: "項目#{l.title}を削除します"},
                        class: "btn btn-info"
                      }
                    )
                  %>
                  <%= link_to("再学習", relearn_learning_path(l.id),
                      { method: :relearn,
                        data: { confirm: "項目#{l.title}を再学習します"},
                        class: "btn btn-info"
                      }
                    )
                  %>
                  <%= link_to "編集", edit_learning_path(l.id), class: "btn btn-info" %>

                  <%= link_to "チェック", check_item_learning_path(l.id),
                      { method: :check_item,
                        class: "btn btn-success"
                      }
                  %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/learnings/new.html.erb
<div class="container">
  <div class="container-fluid">
    <div class="row">
        <div class="col-md-9">
          <h3><%= t('.New Item')%></h3>
          <%= render 'learning_form' %>
        <br>
        <div class="btn-group">
          <%= link_to '一覧に戻る', learnings_path, class: "btn btn-secondary" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/learnings/show.html.erb
<h1>Learnings#show</h1>

<%= link_to 'Edit', edit_learning_path%> |
<%= link_to 'Back', learnings_path %>