config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'learnings#index'

  resources :learnings do
    collection do
      get :history
      get :search
    end
    member do
      post :check_item
      post :relearn
    end
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :users, only: [:show]

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RR</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark sticky-top">
  <div class="container">
    <a class="navbar-brand ">Recurring Reminder</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-content" aria-controls="navbar-content" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    <div class="collapse navbar-collapse small" id="navbar-content">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "学習項目一覧", learnings_path, class: "nav-link" if user_signed_in?  %>
          </li>
          <li class="nav-item">
            <%= link_to "学習履歴", history_learnings_path, class: "nav-link" if user_signed_in? %>
          </li>
          <li class="nav-item">
            <%= link_to "新規登録画面", new_user_registration_path, class: "nav-link" unless user_signed_in? %>
          </li>
          <li class="nav-item">
            <%= link_to "ログイン画面", new_user_session_path, class: "nav-link" unless user_signed_in? %>
          </li>
        </ul>
      <% if user_signed_in? %>
          <ul class="navbar-nav">
            <li class="nav-item btn btn-primary text-black btn-sm">
              <%= link_to '学習項目の新規作成', new_learning_path, class: "nav-link"%>
            </li>
          </ul>
        <ul class="navbar-nav">
      <li class="nav-item text-white">
        　本日の項目数:
        <%= current_user.learnings.where(reappearance_date: "1900-01-01".to_date..Time.zone.today)
                                  .or(current_user.learnings.where(checked_times: 0))
                                  .count %>
      </li>
    </ul>
      <ul class="navbar-nav">
        <li class="nav-item text-white">
          <%= link_to "　ログイン中ユーザー: #{current_user.email}", user_path(id: current_user.id), class: "nav-link" if user_signed_in? %>
        </li>
      </ul>
      <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link"%>
      </li>
    </ul>
      <% end %>
    </div>
  </div>
</nav>
  <div class="jumbotron fixed-bg">
      <ul style="list-style: none;">
        <% if flash.notice.present?%>
          <li><p class="alert alert-notice"><%= notice %></p></li>
        <% elsif flash.alert.present?%>
          <li><p class="alert alert-error"><%= alert %></p></li>
        <% end %>
      </ul>
        <%= yield %>
      </div>
    <footer class="footer bg-dark fixed-bottom">
      <div class="container d-flex justify-content-end">
        <p class="text-white bg-dark">© Odaka, Tomohisa</p>
      </div>
    </footer>
  </body>
</html>